/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "liaoirczyteepczsiwxg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpYW9pcmN6eXRlZXBjenNpd3hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyNTk0MzcsImV4cCI6MjA3ODgzNTQzN30.bqNtXfl3948WMHQHzJ-yj0w-nl3Etvk3LhIVASAa4SU"